"""modelagem inicial

Revision ID: df960bba0ba5
Revises: 
Create Date: 2026-09-25 18:00:46.867309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df960bba0ba5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indices_economicos_cache',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('indice', sa.Enum('SELIC', 'CDI', 'IPCA', name='indice_valido', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indices_economicos_cache')),
    sa.UniqueConstraint('indice', 'data_referencia', name=op.f('uq_indices_economicos_cache_indice_data_referencia'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    op.create_table('simulacoes',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('valor_veiculo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('valor_entrada', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('taxa_ipca_projetada', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('taxa_fundo_rendimento', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('prazo_meses_fundo', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('prazo_meses_fundo > 0', name=op.f('ck_simulacoes_prazo_meses_fundo_positivo')),
    sa.CheckConstraint('taxa_fundo_rendimento >= 0', name=op.f('ck_simulacoes_taxa_fundo_nao_negativa')),
    sa.CheckConstraint('valor_entrada <= valor_veiculo', name=op.f('ck_simulacoes_valor_entrada_maximo')),
    sa.CheckConstraint('valor_entrada >= 0', name=op.f('ck_simulacoes_valor_entrada_nao_negativo')),
    sa.CheckConstraint('valor_veiculo > 0', name=op.f('ck_simulacoes_valor_veiculo_positivo')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_simulacoes_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simulacoes'))
    )
    with op.batch_alter_table('simulacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulacoes_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('opcoes_financiamento',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('simulacao_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('taxa_juros_mensal', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('prazo_meses', sa.Integer(), nullable=False),
    sa.Column('sistema_amortizacao', sa.Enum('PRICE', 'SAC', name='sistema_amortizacao_valido', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('valor_entrada', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('prazo_meses > 0', name=op.f('ck_opcoes_financiamento_prazo_meses_positivo')),
    sa.CheckConstraint('taxa_juros_mensal >= 0', name=op.f('ck_opcoes_financiamento_taxa_juros_nao_negativa')),
    sa.CheckConstraint('valor_entrada >= 0', name=op.f('ck_opcoes_financiamento_valor_entrada_nao_negativo')),
    sa.ForeignKeyConstraint(['simulacao_id'], ['simulacoes.id'], name=op.f('fk_opcoes_financiamento_simulacao_id_simulacoes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opcoes_financiamento'))
    )
    with op.batch_alter_table('opcoes_financiamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opcoes_financiamento_simulacao_id'), ['simulacao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opcoes_financiamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opcoes_financiamento_simulacao_id'))

    op.drop_table('opcoes_financiamento')
    with op.batch_alter_table('simulacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulacoes_usuario_id'))

    op.drop_table('simulacoes')
    op.drop_table('usuarios')
    op.drop_table('indices_economicos_cache')
    # ### end Alembic commands ###
